version: '3.7'

services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ledger
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0'
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.5.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #change ${YOUR_HOST_IP} to your host ip
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:29092,LISTENER_DOCKER_EXTERNAL://${YOUR_HOST_IP}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    restart: always

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: kibana:7.14.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

  ledger:
    image: ledger:0.1
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
      - elasticsearch
    restart: always

volumes:
  mysql-data:
  zookeeper-data:
  kafka-data:
  es-data:
